export const CREATE_VACANCY = 'CREATE_VACANCY';
export const GET_ALL_VACANCIES = 'GET_ALL_VACANCIES';
export const DELETE_VACANCY='DELETE_VACANCY';

export const GET_VACANCY_BY_ID = 'GET_VACANCY_BY_ID';
export const EDIT_VACANCY='EDIT_VACANCY';
export const SHOULD_UPDATE='SHOULD_UPDATE';

export const SEARCH='SEARCH';
export const PAGINATION='PAGINATION';

export const JOB_TYPE={
  FULL_TIME:"FULL_TIME",
  PART_TIME:"PART_TIME",
  INTERNSHIP:"INTERNSHIP",
  FREELANCE:"FREELANCE"
}