export const CREATE_VACANCY = 'CREATE_VACANCY';
export const GET_ALL_VACANCIES = 'GET_ALL_VACANCIES';
export const DELETE_VACANCY='DELETE_VACANCY';

export const GET_VACANCY_BY_ID = 'GET_VACANCY_BY_ID';


